module Pik

  class BashFile < ScriptFile

    def extname
      ".sh"
    end

    def header
      string =  "#!/bin/sh\n"
      string << "#  This bash script generated by Pik, the\n"
      string << "#  Ruby Manager for Windows\n"
    end  
    
    def call(exe)
      @lines << "#{exe}\n"
      self
    end

    def set(items)
      items.each{|k,v|
        @lines << if v
          v = v.to_bash if v.respond_to? 'to_bash'
          "export #{k}='#{v}'"
        else
          "unset #{k}"
        end
      }
      self
    end

  end

end