module Pik

  class BashFile < ScriptFile

    attr_accessor :file_data, :file_name, :ruby_dir

    def extname
      ".sh"
    end

    def header
      string =  "#!/bin/sh\n"
      string << "#  This bash script generated by Pik, the\n"
      string << "#  Ruby Manager for Windows\n"
    end  
    
    def call(exe)
      @file_data << "#{exe}\n"
      self
    end

    def set(items)
      items.each do |k,v| 
        v = v.to_bash if v.respond_to? 'to_bash'
        @file_data << "export #{k}='#{v}'" 
      end
      self
    end

    def unset(items)
      items.each{|k| @file_data << "unset #{k}=" }
      self
    end

  end

end