module Pik

  class BatchFile < ScriptFile

    def extname
      ".bat"
    end

    def header
      string =  "@ECHO OFF\n\n" 
      string << "::  This batch file generated by Pik, the\n"
      string << "::  Ruby Manager for Windows\n"  
    end  

    def call(bat)
      @lines << "CALL #{bat}\n"
      self
    end

    def set(items)
      items.each{|k,v| @lines << "SET #{k}=#{v}" }
      self
    end

    def copy(src, dest)
      @lines << "copy /y #{src} #{dest}"
    end

  end

end