module Pik
  
  class PowershellFile < ScriptFile

    def extname
      ".ps1"
    end

    def header
      string =  "#  This powshell script generated by Pik, the\n"
      string << "#  Ruby Manager for Windows\n"  
    end  
    
    def call(exe)
      @lines << "#{exe}\n"
      self
    end

    def set(items)
      items.each do |k,v| 
        @lines << if v
          "$ENV:#{k}=\"#{v}\""
        else
          "Remove-Item ENV:#{k}"
        end
      end

      self
    end

  end

end