module Pik
  
  class PsFile < ScriptFile

    attr_accessor :file_data, :file_name, :ruby_dir

    def extname
      ".ps1"
    end

    def header
      string =  "#  This powshell script generated by Pik, the\n"
      string << "#  Ruby Manager for Windows\n"  
    end  
    
    def call(exe)
      @file_data << "#{exe}\n"
      self
    end

    def set(items)
      items.each{|k,v| @file_data << "$ENV:#{k}=\"#{v}\"" }
      self
    end

    def unset(items)
      items.each{|k| @file_data << "Remove-Item ENV:#{k}" }
      self
    end

  end

end