require 'lib/rem/windows_file'
require 'lib/rem/batch_file'
require 'lib/rem/search_path'

describe BatchFile do

	it "should have a header" do
		string =  "@ECHO OFF\n\n" 
		string << "::  This batch file generated by REM, the\n"
		string << "::  Ruby Equipment Manager for Windows\n\n"	
		BatchFile.new("C:/ruby/191/bin/ruby.exe").to_s.should == string	
	end

	it "should generate an ftype command for ruby.exe and rubyw.exe" do
		bf = BatchFile.new("C:/ruby/191/bin/ruby.exe")
		bf.ftype.should == "FTYPE rbfile=ruby.exe \"%1\" %*\n\nFTYPE rbwfile=rubyw.exe \"%1\" %*\n\n"
	end

	it "should generate a path command with the updated ruby path" do
		bf = BatchFile.new("C:/ruby/191/bin/ruby.exe")
		bf.set_path.should match /SET PATH\=.+;C:\\ruby\\191\\bin/
	end
	
end
