

class BatchFile

	def initialize(ruby_exe)
		ruby_exe   = File.expand_path(ruby_exe)
		@ruby_exe  = File.basename(ruby_exe)
		@bin_dir   = WindowsFile.join(File.dirname(ruby_exe))
		@rubyw_exe = 'rubyw.exe'
	end
	
	def update_path
		paths=ENV['PATH'].split(';').map{ |dir| dir =~ /ruby/i ? @bin_dir : dir }
		"SET PATH=#{paths.join(';')}"
	end
	
	def full_path_to(exe)
		WindowsFile.join(@bin_dir, exe)
	end
	
	def ftype(files)
		files.map{|filetype, open_with|
			"FTYPE #{filetype}=#{open_with} \"%1\" %*"
		}
	end

	def to_s
		[ "@ECHO OFF", 
			":: This batch file generated by #{File.basename($0)}",
			ftype( :rbfile => full_path_to(@ruby_exe), :rbwfile => full_path_to(@rubyw_exe) ), 
			update_path
		].join("\n\n")
	end

end
