#!/usr/bin/env ruby

lib = File.join(File.dirname(__FILE__), '..', 'lib')
require File.join(lib, 'pik')

include Pik
log = Log.new

args = ARGV

begin
  config  = ConfigFile.new
  
  args_minus_opts = args.reject{|p| p =~ /^-/}
  
  command = if args_minus_opts.empty?
    Help
  elsif (c = Commands.find(args.first))
    args.shift
    c
  elsif (choice = Command.choose_from(args_minus_opts, config))
    args = [choice] + args
    Use
  end
  
  # if config.empty? && command != Pik::Add
  #   add = Pik::Add.new([], config)
  #   add.execute
  #   add.close
  # end
  
  raise "The command '#{args.join(' ')}' is unknown." unless command
  cmd = command.new(args, config, log)
  cmd.execute
rescue Pik::QuitError
  puts "\nQuitting..."
rescue => e
  log.error(e.message, e.backtrace)
ensure
  cmd.close if cmd
end 
