#!/usr/bin/env ruby

lib = File.join(File.dirname(__FILE__), '..', 'lib')
require File.join(lib, 'pik')

include Pik

args = ARGV

begin
  config  = ConfigFile.new
  
  args_minus_opts = args.reject{|p| p =~ /^-/}
  
  command = if args_minus_opts.empty?
    Help
  elsif (c = Commands.find(args.first))
    args.shift
    c
  elsif (choice = Command.choose_from(args_minus_opts, config))
    args = [choice] + args
    Use
  end
  
  raise "The command '#{args.join(' ')}' is unknown." unless command
  cmd = command.new(args, config)
  cmd.execute
rescue QuitError
  puts "\nQuitting..."
rescue => e
  Pik.print_error(e)
ensure
  cmd.close if cmd
end 
